### ISSUE TITLE
Missing requirements on fresh install

### ISSUE THREAD

**Issue by michael-dickinson-sainsburys** [eamonnfaherty/better-boto#1]
Issue:
On a fresh install, boto3 is not installed automatically, therefore errors are thrown about missing modules

Steps to reproduce:
1. Create a new virtual environment and activate it
2. Install better-boto
3. Enter interactive python shell
4. Import a class, such as ClientContextManager from betterboto.client
```
$ vf new betterboto
Running virtualenv with interpreter /usr/local/bin/python3
Using base prefix '/usr/local/Cellar/python/3.7.2_2/Frameworks/Python.framework/Versions/3.7'
New python executable in /Users/michael.dickinson/.virtualenvs/betterboto/bin/python3.7
Not overwriting existing python script /Users/michael.dickinson/.virtualenvs/betterboto/bin/python (you must use /Users/michael.dickinson/.virtualenvs/betterboto/bin/python3.7)
Installing setuptools, pip, wheel...
done.
(betterboto) pip install better-boto
Collecting better-boto
  Downloading https://files.pythonhosted.org/packages/56/3d/d29f13405c77caa1aee60a86d59d014a5c1f8eb8ad7bfcc28a1526e96ff6/better_boto-0.6.19-py3-none-any.whl
Collecting pyyaml>=4.2b1 (from better-boto)
Installing collected packages: pyyaml, better-boto
Successfully installed better-boto-0.6.19 pyyaml-5.1
(betterboto) python3
Python 3.7.2 (default, Feb 12 2019, 08:16:38) 
[Clang 10.0.0 (clang-1000.11.45.5)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> from betterboto.client import ClientContextManager
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/michael.dickinson/.virtualenvs/betterboto/lib/python3.7/site-packages/betterboto/client.py", line 1, in <module>
    from . import cloudformation
  File "/Users/michael.dickinson/.virtualenvs/betterboto/lib/python3.7/site-packages/betterboto/cloudformation.py", line 4, in <module>
    import botocore
ModuleNotFoundError: No module named 'botocore'
```

**Comment by eamonnfaherty** [comment]
Thanks for the issue and the fix!

**Comment by eamonnfaherty** [comment]
Thanks for the issue and the fix!
